### PR TITLE
Feature/300 intfire

### PR DESCRIPTION
**Pull request by kaeldai**
A new example of 300 IntFire1 cells.

### CODE REVIEW

**Comment by pgleeson** [comment]
@kaeldai Quick question: in this example the positions are represented as a dataset named 'positions' with 2 columns (I assume for X&Y) under the node:
selection_878

In other examples there are 1 column datasets under the node named x, y, z.
- Are both formats supported or is the former the preferred way?
- If so, how is it possible to tell if it's X&Y or X&Z etc?

**Comment by kaeldai** [comment]
@pgleeson Previously SONATA supported a multi-column dataset called "positions", but it's changed to just a single-column datasets "x", "y", "z". The scripts used to build the example are a bit outdated and I will go ahead and fix the example. Thanks for catching that.

**Comment by pgleeson** [comment]
Thanks @kaeldai, works fine for me now.

**Comment by pgleeson** [comment]
@kaeldai I can run the build_network.py fine on this example, but run_bionet.py fails. Should this work with the develop branch of BMTK?

**Comment by kaeldai** [comment]
@pgleeson it should work with the latest develop branch of bmtk. What error(s) are you getting?

**Comment by apdavison** [comment]
In the x_edge_types.csv files, there are columns "target_query" and "source_query", but these names are not mentioned anywhere in the developer's guide. Are they part of the spec? I think such queries will add quite considerably to the complexity of implementing the spec.

**Comment by kaeldai** [comment]
Hi @apdavison - these columns are optional attributes and can/should be ignored. It's added by the bmtk and used by modelers to indicate the rules used to build a set of edges. 

We use these fields to helps us manually adjust network params between simulations without having to rebuild the network. But I understand not all modelers need or want this functionality. We can remove these columns and the network will still run using the bmtk.

**Comment by apdavison** [comment]
@kaeldai Thanks very much for the explanation!

**Comment by apdavison** [comment]
In the `dynamics_params` JSON files (e.g. `shared_components/point_neuron_models_dir/IntFire1_exc_1.json`), the parameters `tau` and `refrac` are given in seconds, but the IntFire1 mechanism expects values in milliseconds.

I can't see any information about units either in the data/parameter/config files for this example, or in the developers' guide.

**Comment by apdavison** [comment]
The `nsyns` parameter is not mentioned in the spec.

**Comment by apdavison** [comment]
This example now working in PyNN (serialization branch):

bmtk_pynn_comparison

```python
from pyNN.serialization import import_from_sonata, load_sonata_simulation_plan
import pyNN.neuron as sim

simulation_plan = load_sonata_simulation_plan("simulation_config.json")
simulation_plan.setup(sim)
net = import_from_sonata("circuit_config.json", sim)
simulation_plan.execute(net)
```

**Comment by pgleeson** [comment]
Just checking, but any reason this example hasn't been merged to master yet?

**Comment by hernando** [comment]
I haven't followed this discussion, but right now there are conflicts. Can you take a look @kaeldai?

**Pull request merged**
